variables:
  VLC40_IMAGE: registry.videolan.org/vlc-debian-unstable:20230705133021

build:
  image: $VLC40_IMAGE
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_PROJECT_PATH == "videolan/libvlcpp" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  tags:
    - docker
    - amd64
  script:
    - export CXXFLAGS="-Werror" # Mainly to fail on deprecation errors.
    - export VLC_PLUGIN_PATH="${CI_PROJECT_DIR}/build/subprojects/libvlc/modules/"
    - meson setup build -Dexamples=enabled -Dtests=enabled --native-file subprojects/packagefiles/libvlc/libvlc-minimal.ini
    - meson compile -C build
    - meson test -C build "libvlcpp:"
  artifacts:
    reports:
      junit: build/meson-logs/testlog.junit.xml
    paths:
      - ${CI_PROJECT_DIR}/build/meson-logs/testlog.txt
    when: always
