/*****************************************************************************
 * libvlc_Media.cpp: Media implementation
 *****************************************************************************
 * Copyright © 2014 the VideoLAN team
 *
 * Authors: Alexey Sokolov <alexey@alexeysokolov.co.cc>
 *          Hugo Beauzée-Luyssen <hugo@beauzee.fr>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston MA 02110-1301, USA.
 *****************************************************************************/

/* This file is autogenerated */


#include <vlc.hpp>

namespace VLC {

Media* Media::fromPath(Instance& instance, const std::string& path)
{
    InternalPtr ptr = libvlc_media_new_path( instance, path.c_str() );
    if ( ptr == NULL )
        return NULL;
    return new Media(ptr);
}

Media*Media::fromLocation(Instance& instance, const std::string& location)
{
    InternalPtr ptr = libvlc_media_new_location( instance, location.c_str() );
    if ( ptr == NULL )
        return NULL;
    return new Media(ptr);
}

Media*Media::fromFileDescriptor(Instance& instance, int fd)
{
    InternalPtr ptr = libvlc_media_new_fd( instance, fd );
    if ( ptr == NULL )
        return NULL;
    return new Media( ptr );
}

Media*Media::fromList(MediaList& list)
{
    InternalPtr ptr = libvlc_media_list_media( list );
    if ( ptr == NULL )
        return NULL;
    return new Media( ptr );
}

Media*Media::asNode(Instance& instance, const std::string& nodeName)
{
    InternalPtr ptr = libvlc_media_new_as_node( instance, nodeName.c_str() );
    if ( ptr == NULL )
        return NULL;
    return new Media( ptr );
}

Media::Media(const Media& another)
{
    m_obj = another.m_obj;
    retain();
}

const Media& Media::operator=(const Media& another) 
{
    if (this == &another) 
    {
        return *this;
    }
    release();
    m_obj = another.m_obj;
    retain();
    return *this;
}

bool Media::operator==(const Media& another) const 
{
    return m_obj == another.m_obj;
}

Media::~Media() 
{
    release();
}

void Media::addOption(const std::string& psz_options) 
{
    libvlc_media_add_option(m_obj, psz_options.c_str());
}

void Media::addOptionFlag(const std::string& psz_options, unsigned i_flags) 
{
    libvlc_media_add_option_flag(m_obj, psz_options.c_str(), i_flags);
}

std::string Media::mrl() 
{
    char * c_result = libvlc_media_get_mrl(m_obj);
    std::string result = c_result;
    libvlc_free(c_result);
    return result;
}

Media Media::duplicate() 
{
    libvlc_media_t * c_result = libvlc_media_duplicate(m_obj);
    Media result = c_result;
    return result;
}

std::string Media::meta(libvlc_meta_t e_meta) 
{
    char * c_result = libvlc_media_get_meta(m_obj, e_meta);
    std::string result = c_result;
    libvlc_free(c_result);
    return result;
}

void Media::setMeta(libvlc_meta_t e_meta, const std::string& psz_value) 
{
    libvlc_media_set_meta(m_obj, e_meta, psz_value.c_str());
}

int Media::saveMeta() 
{
    int c_result = libvlc_media_save_meta(m_obj);
    int result = c_result;
    return result;
}

libvlc_state_t Media::state() 
{
    libvlc_state_t c_result = libvlc_media_get_state(m_obj);
    libvlc_state_t result = c_result;
    return result;
}

bool Media::stats(libvlc_media_stats_t * p_stats) 
{
    int c_result = libvlc_media_get_stats(m_obj, p_stats);
    bool result = c_result;
    return result;
}

libvlc_event_manager_t * Media::eventManager() 
{
    libvlc_event_manager_t * c_result = libvlc_media_event_manager(m_obj);
    libvlc_event_manager_t * result = c_result;
    return result;
}

libvlc_time_t Media::duration() 
{
    libvlc_time_t c_result = libvlc_media_get_duration(m_obj);
    libvlc_time_t result = c_result;
    return result;
}

void Media::parse() 
{
    libvlc_media_parse(m_obj);
}

void Media::parseAsync() 
{
    libvlc_media_parse_async(m_obj);
}

bool Media::isParsed() 
{
    int c_result = libvlc_media_is_parsed(m_obj);
    bool result = c_result;
    return result;
}

void Media::setUserData(void * p_new_user_data) 
{
    libvlc_media_set_user_data(m_obj, p_new_user_data);
}

void * Media::userData() 
{
    void * c_result = libvlc_media_get_user_data(m_obj);
    void * result = c_result;
    return result;
}

std::vector<MediaTrack> Media::tracks()
{
    libvlc_media_track_t**  tracks;
    uint32_t                nbTracks = libvlc_media_tracks_get(m_obj, &tracks);
    std::vector<MediaTrack> res;

    if ( nbTracks == 0 )
        return res;

    for ( uint32_t i = 0; i < nbTracks; ++i )
        res.push_back( MediaTrack(tracks[i]));
    libvlc_media_tracks_release( tracks, nbTracks );
    return res;
}

Media::Media(Internal::InternalPtr ptr)
    : Internal(ptr)
{
}

void Media::retain() 
{
    libvlc_media_retain(m_obj);
}

void Media::release() 
{
    libvlc_media_release(m_obj);
}

} // namespace VLC

