/*****************************************************************************
 * vlc.hpp: Main VLC++ header.
 *****************************************************************************
 * Copyright © 2014 the VideoLAN team
 *
 * Authors: Alexey Sokolov <alexey@alexeysokolov.co.cc>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston MA 02110-1301, USA.
 *****************************************************************************/

/* This file is autogenerated */



#ifndef LIBVLC_CXX_VLC_H
#define LIBVLC_CXX_VLC_H

#include <libvlc_Instance.hpp>
#include <libvlc_MediaListPlayer.hpp>
#include <libvlc_MediaDiscoverer.hpp>
#include <libvlc_MediaPlayer.hpp>
#include <libvlc_Media.hpp>
#include <libvlc_MediaLibrary.hpp>
#include <libvlc_MediaList.hpp>
#include <libvlc_EventManager.hpp>

#endif
